import {
  Article,
  Category,
  ContentForm,
  CurrUserState,
  ListPageState,
  Role,
  SITE_STATUS,
  Site,
} from '@/types/types'

import { DEFAULT_PAGE_SIZE } from './constants'

export const defaultSite: Site = {
  id: 0,
  name: '',
  frontId: '',
  visible: true,
  creatorId: '0',
  creatorName: '',
  logoUrl: '',
  logoHtmlStr: '',
  description: '',
  keywords: '',
  rulesArticleId: 0,
  boardCategoryId: 0,
  createdAt: '',
  updatedAt: '',
  status: SITE_STATUS.Pending,
  categoryFrontIds: [],
  currUserRole: null,
  currUserState: {
    isMember: false,
  },
  allowNonMemberInteract: false,
  homePage: '/',
  deleted: false,
  memberCount: 0,
  onlineCount: 0,
  reviewBeforePublish: false,
  uiSettings: null,
  rateLimitTokens: 15,
  rateLimitInterval: 60,
  rateLimitEnabled: false,
}

export const defaultCategory: Category = {
  id: '0',
  frontId: '',
  name: '',
  describe: '',
  authorId: '',
  createdAt: '',
  approved: false,
  approvalComment: '',
  totalArticleCount: 0,
  siteId: 0,
  siteFrontId: '',
  iconBgColor: '',
  iconContent: '',
  contentFormId: '',
  contentForm: null,
  userState: null,
  visible: true,
}

export const defaultContentForm: ContentForm = {
  id: '0',
  name: '',
  frontId: '',
  description: '',
  creatorId: '',
  creatorName: '',
  createdAt: '',
  statusList: null,
}

export const defaultCurrState: CurrUserState = {
  voteType: 'up',
  saved: false,
  reactFrontId: '',
  subscribed: false,
  isRead: false,
}

export const defaultArticle: Article = {
  id: '0',
  title: '',
  displayTitle: '',
  asMainArticle: false,
  link: '',
  picURL: '',
  price: 0,
  authorName: '',
  authorRoleName: '',
  showAuthorRoleName: false,
  authorId: '',
  content: '',
  summary: '',
  createdAt: '',
  updatedAt: '',
  createdAtStr: '',
  updatedAtStr: '',
  replyToId: '',
  replyToArticle: null,
  replyRootAuthorId: '',
  deleted: false,
  replies: null,
  totalReplyCount: 0,
  totalSavedCount: 0,
  childrenCount: 0,
  voteUp: 0,
  voteDown: 0,
  voteScore: 0,
  weight: 0,
  listWeight: 0,
  participateCount: 0,
  currUserState: { ...defaultCurrState },
  reactCounts: {},
  showScore: false,
  categoryId: '0',
  categoryFrontId: '',
  category: { ...defaultCategory },
  locked: false,
  pinned: false,
  pinnedExpireAt: '',
  pinnedScope: '',
  blocked: false,
  fadeOut: false,
  replyRootArticleId: '',
  replyRootArticleTitle: '',
  replyRootArticleSiteFrontId: '',
  delLog: null,
  siteFrontId: '',
  site: { ...defaultSite },
  status: 'draft',
  version: 0,
  hasReviewing: false,
  contentFormId: '0',
  contentForm: null,
  contentStatusId: '',
  contentStatus: null,
  acceptAnswerId: '0',
  viewCount: 0,
  articleLinkClick: 0,
  tags: [],
}

export const defaultPageState: ListPageState = {
  currPage: 1,
  pageSize: DEFAULT_PAGE_SIZE,
  total: 0,
  totalPage: 0,
}

export const defaultRole: Role = {
  id: '',
  frontId: '',
  name: '',
  createdAt: '',
  deleted: false,
  isSystem: false,
  permissions: null,
  formattedPermissions: [],
  level: 3,
  relateUserCount: 0,
  siteNumLimit: 0,
  showRoleName: false,
  rateLimitTokens: 15,
  rateLimitInterval: 60,
  rateLimitEnabled: false,
}
