import {
  Article,
  Category,
  CurrUserState,
  ListPageState,
  SITE_STATUS,
  Site,
} from '@/types/types'

import { DEFAULT_PAGE_SIZE } from './constants'

export const defaultSite: Site = {
  id: 0,
  name: '',
  frontId: '',
  visible: true,
  creatorId: '0',
  creatorName: '',
  logoUrl: '',
  logoHtmlStr: '',
  description: '',
  keywords: '',
  rulesArticleId: 0,
  boardCategoryId: 0,
  createdAt: '',
  updatedAt: '',
  status: SITE_STATUS.Pending,
  categoryFrontIds: [],
  currUserRole: null,
  currUserState: {
    isMember: false,
  },
  allowNonMemberInteract: false,
  homePage: '/',
  deleted: false,
  memberCount: 0,
  onlineCount: 0,
  reviewBeforePublish: false,
}

export const defaultCategory: Category = {
  id: '',
  frontId: '',
  name: '',
  describe: '',
  authorId: '',
  createdAt: '',
  approved: false,
  approvalComment: '',
  totalArticleCount: 0,
  siteId: 0,
  siteFrontId: '',
}

export const defaultCurrState: CurrUserState = {
  voteType: 'up',
  saved: false,
  reactFrontId: '',
  subscribed: false,
}

export const defaultArticle: Article = {
  id: '',
  title: '',
  displayTitle: '',
  asMainArticle: false, // 是否在前端作为顶层文章
  link: '',
  picURL: '',
  price: 0,
  authorName: '',
  authorId: '',
  content: '',
  summary: '',
  createdAt: '',
  updatedAt: '',
  createdAtStr: '',
  updatedAtStr: '',
  replyToId: '',
  replyToArticle: null,
  replyRootAuthorId: '',
  deleted: false,
  replies: null,
  totalReplyCount: 0,
  totalSavedCount: 0,
  childrenCount: 0,
  voteUp: 0,
  voteDown: 0,
  voteScore: 0,
  weight: 0,
  listWeight: 0,
  participateCount: 0,
  currUserState: { ...defaultCurrState },
  showScore: false,
  categoryId: '0',
  categoryFrontId: '',
  category: { ...defaultCategory },
  locked: false,
  pinned: false,
  pinnedExpireAt: '',
  blocked: false,
  fadeOut: false,
  replyRootArticleId: '',
  replyRootArticleTitle: '',
  replyRootArticleSiteFrontId: '',
  delLog: null,
  siteFrontId: '',
  site: { ...defaultSite },
  status: 'draft',
  version: 0,
  hasReviewing: false,
}

export const defaultPageState: ListPageState = {
  currPage: 1,
  pageSize: DEFAULT_PAGE_SIZE,
  total: 0,
  totalPage: 0,
}
