export const ROLE_LIST = ['common_user', 'banned_user', 'moderator', 'admin']

export const ROLE_DATA = {
  common_user: {
    level: 3,
    name: '普通用户',
    adapt_id: 'common_user',
    permissions: [
      'article.create',
      'article.reply',
      'article.edit_mine',
      'article.save',
      'article.react',
      'article.delete_mine',
      'article.vote_up',
      'article.subscribe',
      'user.update_intro_mine',
    ],
  },
  banned_user: {
    level: 4,
    name: '受限用户',
    adapt_id: 'banned_user',
    permissions: null,
  },
  moderator: {
    level: 2,
    name: '版主',
    adapt_id: 'moderator',
    permissions: [
      'article.create',
      'article.reply',
      'article.edit_mine',
      'article.save',
      'article.react',
      'article.delete_mine',
      'article.vote_up',
      'article.vote_down',
      'article.subscribe',
      'user.update_intro_mine',
      'article.edit_others',
      'article.delete_others',
      'article.view_score',
      'article.pin',
      'article.lock',
      'reply.edit_others',
      'reply.delete_others',
      'user.manage',
      'user.access_activity',
      'user.update_role',
      'user.ban',
      'user.update_intro_others',
    ],
  },
  admin: {
    level: 1,
    name: '管理员',
    adapt_id: 'admin',
    permissions: [
      'article.create',
      'article.reply',
      'article.edit_mine',
      'article.save',
      'article.react',
      'article.delete_mine',
      'article.vote_up',
      'article.vote_down',
      'article.subscribe',
      'user.update_intro_mine',
      'article.edit_others',
      'article.delete_others',
      'article.view_score',
      'article.pin',
      'article.lock',
      'reply.edit_others',
      'reply.delete_others',
      'user.manage',
      'user.update_role',
      'user.ban',
      'user.update_intro_others',
      'user.list_access',
      'user.set_moderator',
      'user.access_activity',
      'user.access_manage_activity',
      'manage.access',
      'permission.access',
      'role.access',
      'role.add',
      'role.edit',
      'activity.access',
      'category.create',
      'category.edit',
      'category.delete',
    ],
  },
}

export const MIN_ROLE_LEVEL = 2
