import { Page } from '@playwright/test'

export const adminAccount = {
  username:
    process.env.E2E_ADMIN_USERNAME || process.env.SUPER_USER || 'testsadmin',
  email:
    process.env.E2E_ADMIN_EMAIL ||
    process.env.SUPER_USER_EMAIL ||
    'testsadmin@example.com',
  password:
    process.env.E2E_ADMIN_PASSWORD ||
    process.env.SUPER_PASSWORD ||
    'TestsAdmin123!',
}

export const config = {
  superVerifyCode: process.env.E2E_SUPER_VERIFY_CODE || '686868',
  testEmailPrefix: process.env.E2E_TEST_EMAIL_PREFIX || 'test-',
  testEmailDomain: process.env.E2E_TEST_EMAIL_DOMAIN || '@example.com',
  testPhonePrefix: process.env.E2E_TEST_PHONE_PREFIX || '13800138',
  testPassword: process.env.E2E_TEST_PASSWORD || 'TestPass123!',
}

export function generateRandomEmail(): string {
  const timestamp = Date.now()
  const random = Math.floor(Math.random() * 10000)
  return `${config.testEmailPrefix}${timestamp}${random}${config.testEmailDomain}`
}

export function generateRandomPhone(): string {
  const random = Math.floor(Math.random() * 1000)
    .toString()
    .padStart(3, '0')
  return `${config.testPhonePrefix}${random}`
}

export function generateRandomUsername(): string {
  const timestamp = Date.now()
  const random = Math.floor(Math.random() * 1000)
  return `user${timestamp}${random}`.toLowerCase()
}

const randomShortId = (prefix: string, length: number) => {
  const random = Math.random()
    .toString(36)
    .slice(2, 2 + length)
  const time = Date.now().toString(36).slice(-length)
  return `${prefix}${time}${random}`.slice(0, prefix.length + length * 2)
}

export function generateRandomSiteFrontId(): string {
  return randomShortId('site', 4)
}

export function generateRandomSiteName(): string {
  const random = Math.floor(1000 + Math.random() * 9000)
  return `Site${random}`
}

export function generateRandomCategoryFrontId(): string {
  return randomShortId('bk', 5)
}

export function generateRandomCategoryName(): string {
  const random = Math.floor(100 + Math.random() * 900)
  return `Bank${random}`
}

export function generateRandomArticleTitle(): string {
  return `Article ${Date.now().toString(36)}`
}

export function generateRandomArticleContent(): string {
  return `Automated content ${Date.now().toString(36)} generated by e2e tests.`
}

export async function fillVerificationCode(
  page: Page,
  code: string = config.superVerifyCode
): Promise<void> {
  await page.getByPlaceholder(/Verification Code/i).fill(code)
}

export async function clickNextStep(page: Page): Promise<void> {
  await page.getByRole('button', { name: /Next/i }).click()
}

export async function clickSubmit(page: Page): Promise<void> {
  await page.getByRole('button', { name: /Submit/i }).click()
}

export async function waitForSignupSuccess(page: Page): Promise<void> {
  await page.waitForURL('/', { timeout: 10000 })
}

export async function waitForSigninSuccess(page: Page): Promise<void> {
  await page.waitForURL('/', { timeout: 10000 })
}

export async function signInAsAdmin(page: Page): Promise<void> {
  await page.goto('/signin')
  const identifier = adminAccount.email || adminAccount.username
  await page.getByPlaceholder(/Username or Email/i).fill(identifier)
  await page.getByPlaceholder(/Password/i).fill(adminAccount.password)
  await page.getByRole('button', { name: /Sign in/i }).click()
  await waitForSigninSuccess(page)
}

export async function logout(page: Page): Promise<void> {
  await page.goto('/')
  const userMenuButton = page.locator('[data-testid="user-menu"]').first()
  if ((await userMenuButton.count()) > 0) {
    await userMenuButton.click()
    await page.getByRole('menuitem', { name: /退出|Logout/i }).click()
  }
}
